version: 0.2

phases:
  install:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
artifacts:
  files:
    - '**/*'
  name: output-$(date +%Y-%m-%d)
  secondary-artifacts:
    artifactsCodeBuildStorage:
      files:
        - '**/*'
      name: allrepository-artifact-1